# Generated by Django 3.1 on 2020-12-13 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_auto_20201210_1736'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='statues',
            field=models.BooleanField(default=False),
        ),
    ]
